### ISSUE TITLE
Request Detailed Setup and Execution Instructions

### ISSUE THREAD

**Issue by iineon123** [caymansimpson/EliteFurretAI#2]
I'm excited about using EliteFurretAI but found the setup and execution process challenging due to limited documentation. Could you provide a detailed guide covering:

Execution Steps: Commands and scripts required to run the project.

Such enhancements would significantly improve usability and accessibility for all users.

Thank you for considering this improvement.

**Comment by caymansimpson** [comment]
EliteFurretAI is still early in development; it's not functional yet. I'm guessing it will take me another 6 months to get the basic utilities done (battle serialization, speed parsing, damage calculations and reverse damage calculations) before I start exploring the modeling side!

I put together a doc to get it (w/ showdown and poke-env) up and running [here](https://docs.google.com/document/d/1QlrOuvNUQYl4ZLsBvRUHDqjQ9ibm61Nq4lrAJfjQjpE/edit#). Feel free to let me know if you have any further questions or if you'd like to contribute
